application: imf-tweet
version: 1
runtime: python
api_version: 1

handlers:
- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt
- url: /images
  static_dir: static/images
- url: /remove
  script: taskworker.py
  login: admin
- url: /.*
  script: index.py
